### ISSUE TITLE
`run_tests.sh` does not support iCnC

### ISSUE THREAD

**Issue by cogumbreiro** [habanero-rice/cnc-framework#4]
Hi,

I'm trying to setup CnC but having some problems with it.

I installed iCnC, setup the environment variables:
```
   $ source ~/Software/icnc/bin/cncvars.sh 
   Overwriting existing TBB settings.
   $ source setup_env.sh 
   Using existing $CNCROOT (iCnC)
   Set $UCNC_ROOT
   Updated $PATH
   Setup complete.
```

When I tried running `run_tests.sh` it failed:

```
$ ./test/run_tests.sh 
>>> Running test BigTags
    FAILED

>>> Running test EvenOddSums
    FAILED

>>> Running test Range3D
    FAILED

>>> Running test Stencil1D
    FAILED

Ran 4 tests, with 4 failures.
See '/home/tiago/Work/cnc-framework/test/test.log' for details.

```

Here's the error log I got:
[test.log](https://github.com/habanero-rice/cnc-framework/files/1106733/test.txt)

Any ideas on what I'm doing  wrong?

**Comment by agrippa** [comment]
I am by no means a CnC expert (quite the opposite), but I do see the following error message in the attached log:

Please define XSTG_ROOT or OCR_INSTALL_ROOT

Do you have OCR installed, and have the OCR_INSTALL_ROOT environment variable pointing to it?

**Comment by cogumbreiro** [comment]
Let me clarify my problem. I am trying to setup CnC and am following the README. *I think this is an error in the documentation.* I've updated the title of the issue to clarify the error.

The README states:

> You will also need one or more of the supported runtime backends:
> * OCR 1.1
> * Intel CnC

Further along it states I should invoke `./test/run_tests.sh` but that script failed, with the uploaded log.

Additionally, is it possible that my CnC installation is already correctly installed and `run_tests.sh` simply does not handle only having iCnC? Note that as the log correctly mentions I haven't installed XSTG and OCR but these two requirements are optional as per the documentation.

**Comment by DaoWen** [comment]
FYI, there is an environment variable you can set to change how the translator tool is invoked by the test script:

    CNC_T='ucnc_t -p icnc' ./test/run_tests.sh

However, I like your solution in #8 (and the fact that you updated the README). I think passing the arguments directly to the test script is more intuitive for a user verifying the installation, rather than having to set the environment variable with the full command for invoking the translator with the desired platform configuration.

**Comment by DaoWen** [comment]
Thanks for the pull request! It's been merged.
