### ISSUE TITLE
Don't include trailing whitespace in parser's longest-suffix error messages

### ISSUE THREAD

**Issue by DaoWen** [habanero-rice/cnc-framework#7]
This was motivated by issue #5.

I added some [custom error-handling code](https://github.com/habanero-rice/cnc-framework/blob/1ec49ba8/tools/cncframework/parser.py#L4-L44) to wrap the PyParsing-based CnC spec parsers, which lets the parser author inject useful error diagnostics as alternatives in the grammar (a la the Scala parser combinator library). There's some bookkeeping to keep track of the error corresponding to the *longest* match, whereas the default is to report the most recent failure (which is not usually very helpful). However, the line+col reporting for the position of the error often follows whitespace that trails after the meaningful symbols—which is not ideal. It would be good to un-slurp trailing whitespace for these errors if possible.

Specifically, in the message reported in #5, the error reports that it expects a delimiter just before the `(` for the step collection reference, which is a linebreak and a tab/indent after where a human would expect the delimiter to be (i.e., just after the `]` on the previous line).

**Comment by cogumbreiro** [comment]
@DaoWen, what was issue #5? It seems that the issues disappeared somehow, because I created the current issue #5 and it is unrelated to what is being discussed here.

**Comment by DaoWen** [comment]
No, I'm talking about your #5. I was referring to the ParseException message that you reported:

    pyparsing.ParseException: Expected delimiter: ';' (at char 317), (line:13, col:5)

I'm saying it would have been more helpful if it said this instead:

    pyparsing.ParseException: Expected delimiter: ';' (at char 312), (line:12, col:45)

The message it's giving now is still *much* more helpful than what it did originally (since PyParsing backtracks, and reports the *most recent* error by default, it would have said it was expecting a valid step declaration back on line 9 or something); however, if it's not a ton of work I think un-slurping the whitespace might make this even more clear. If we get really ambitious, we could even do something like Clang does and print the line with an arrow to the position in question:
```
    [ fromRight: $range(0, NUM_TILES-1), 0 ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by cogumbreiro** [comment]
Sorry for the noise then. I thought this issue was older than mine and got super confused.

And yeah, totally agree with improving the UX of these error messages.
